<?php
/**
 * Created by PhpStorm.
 */

namespace frontend\widgets\RequestItemWidget;

use common\models\Request;
use yii\base\InvalidConfigException;
use yii\base\Widget;

/**
 * Class RequestItemWidget
 *
 * @extends Widget
 * @package frontend\widgets\RequestItemWidget
 */
class RequestItemWidget extends Widget
{
    /** @var Request request model */
    public $model;

    private $answers;

    /**
     * @throws InvalidConfigException
     */
    public function init()
    {
        if (empty($this->model)) {
            throw new InvalidConfigException("The RequestWidget 'model' has not been set.");
        }

        $this->answers = $this->model->requestAnswers;
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * Runs the widget.
     * @inheritDoc
     */
    public function run()
    {
        // render html view
        return $this->renderNeededView();
    }

    /**
     * @return string
     */
    public function renderNeededView()
    {
        $view = $this->getView();

        RequestItemWidgetAsset::register($view);

        $dependencyArray = [
            'model'   => $this->model,
            'answers' => $this->answers,
        ];

        return $this->render('_view', $dependencyArray);
    }
}